import Head from "next/head";
import * as React from 'react';

import { FormProvider, FormProviderProps, useForm } from 'react-hook-form';
import { useMutation } from '@tanstack/react-query';
import { useRouter } from 'next/router';
import toast, {Toaster} from "react-hot-toast";
import { apiMock } from '@/lib/apiMock';

import { Carousel } from '@mantine/carousel';
import Layout from "@/Layout/Layout";
import { Search, PlayerTrackNext, PlayerTrackPrev } from 'tabler-icons-react';
import type { InferGetStaticPropsType, GetStaticProps } from 'next';

export type IdData={
    id: String;
}

export type SearchData = {
    keyword: string;
}

// perlu revisi style pake tailwind
export default function GamePage(){
    const router = useRouter();
    const { id } = router.query;
    const [openTab, setOpenTab] = React.useState(1);
    //const user = await apiMock.get(`https://fp-mbd-backend-production-77db.up.railway.app/user/game/${id}`)

    const { mutate, isSuccess, isError, isLoading } = useMutation(
        async ({keyword}: SearchData) => {
            await toast.promise(
              apiMock.post(`https://fp-mbd-backend-production-77db.up.railway.app/user`, {keyword}) //sesuaikan API
             .then( async (res) => {
               console.log(res)
               const data = res.data.data;
            }),
            {
              success: 'Search successful',
              loading: 'Loading...',
              error: (e) =>{
                return <p>
                  {e.response ? e.response.data.message : 'Something went wrong'}
                </p>;
              }
            }
            )}
          )

    const onSubmit = ({keyword}: SearchData) => {
        //console.log("data", {email, password}); //dummy test
        mutate({keyword});
    }

    const methods = useForm<SearchData>({
        mode: "onChange",
        defaultValues: {
          keyword: "",
        }
      });
    
      const {
        handleSubmit,
        formState,
        reset,
        formState: { errors },
      } = methods;

      React.useEffect(() => {
        if (formState.isSubmitSuccessful) {
          reset({
            keyword: "",
          });
        }
      }, [formState, reset]);
    
    return( 
        <>
            <Head>
                <title>Game Page</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <main className="bg-blue-200 dark:bg-slate-800">
                    <div className="px-[15%] pt-5">
                        <FormProvider {...methods}>
                            <form onSubmit={handleSubmit(onSubmit)}>
                                <label htmlFor="default-search" className="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-white">Search</label>
                                <div className="relative">
                                    <div className="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                                        <svg aria-hidden="true" className="w-5 h-5 text-gray-500 dark:text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path></svg>
                                    </div>
                                    <input type="search" id="default-search" className="block w-full p-4 pl-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Search Games, Tags..." required/>
                                    <button type="submit" className="text-white absolute right-2.5 bottom-2.5 bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"><Search size={20} color="white"/></button>
                                </div>
                            </form>
                        </FormProvider>
                    </div>
                    <div className="container w-10/12 flex flex-col px-0 mt-1 mx-auto">
                        <p className="ml-2 mt-10 mb-5 font-medium text-2xl">Counter Strike: Global Offensive</p>

                        <div className="container w-full flex flex-col-reverse md:flex-row px-0 bg-slate-900">
                            <div className="w-full flex md:w-2/3 p-0">
                                <div className="embed-responsive embed-responsive-16by9 align-center w-full my-auto">
                                    <iframe className="w-full aspect-video embed-responsive-item" src="https://cdn.akamai.steamstatic.com/steam/apps/81958/movie480.webm?t=1554409259"></iframe>
                                </div>
                            </div>

                            <div className="w-full md:w-1/3 p-3">
                                <img src="https://drive.google.com/uc?export=view&id=1UOX9hzioGUnmgNYEeA2lBtEmson4YIwU" className="img-fluid w-full h-auto" alt="Game image"/>
                                <div className="G-desk m-2">
                                    <p className="my-0 text-light text-lg">The most played online PC action game in the world</p><br/>
                                    <p className="mt-1 mb-0 text-light font-light text-lg" >Release Date: [G_TGLRILIS]</p>
                                    <p className="mt-1 mb-0 text-light font-light text-lg" >Developer: [Developer_D_ID]</p>
                                    <p className="mt-1 mb-0 text-light font-light text-lg" >Release Date: [G_TGLRILIS]</p>
                                    <p className="mt-1 mb-0 text-light font-light text-lg" >Age Rating: [G_AGERATING]</p>
                                    <p className="mt-1 mb-0 text-light font-light text-lg" >Tags:</p>
                                    <div className="badge bg-primary text-wrap w-16">
                                        [G_TAGS].
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div className="container flex flex-col md:flex-row px-0 mt-3">
                            
                            <div className="container w-full md:w-2/3 flex flex-col m-0 p-0 h-100">

                                <div className="w-full bg-slate-700 block rounded p-5">
                                    <h5 className="ml-2 mt-4 font-medium text-lg w-2/3">Play Counter Strike: Global Offensive</h5>

                                    <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded float-right">
                                        Rp 10.000,-
                                    </button>
                                </div>

                                <div className="container col-12 my-2 py-3 cust-container-top">
                                    <div className="w-full bg-slate-900 p-5">
                                        <div className="flex flex-wrap">
                                            <div className="w-full">
                                            <ul
                                                className="w-full lg:w-1/3 flex mb-0 list-none pb-4 flex-row"
                                                role="tablist"
                                            >
                                                <li className="-mb-px mr-2 last:mr-0 flex-auto text-center">
                                                <a
                                                    className={
                                                    "text-xs font-bold uppercase px-5 py-3 shadow-lg rounded block leading-normal " +
                                                    (openTab === 1
                                                        ? "text-white bg-slate-700"
                                                        : "text-white bg-blueGray-600")
                                                    }
                                                    onClick={e => {
                                                    e.preventDefault();
                                                    setOpenTab(1);
                                                    }}
                                                    data-toggle="tab"
                                                    href="#link1"
                                                    role="tablist"
                                                >
                                                    Minimum
                                                </a>
                                                </li>
                                                <li className="-mb-px mr-2 last:mr-0 flex-auto text-center">
                                                <a
                                                    className={
                                                    "text-xs font-bold uppercase px-5 py-3 shadow-lg rounded block leading-normal" +
                                                    (openTab === 2
                                                        ? "text-white bg-slate-700"
                                                        : "text-white bg-blueGray-600")
                                                    }
                                                    onClick={e => {
                                                    e.preventDefault();
                                                    setOpenTab(2);
                                                    }}
                                                    data-toggle="tab"
                                                    href="#link2"
                                                    role="tablist"
                                                >
                                                    Recommended
                                                </a>
                                                </li>
                                            </ul>
                                            <div className="relative flex flex-col min-w-0 break-words w-full mb-6 shadow-lg rounded bg-slate-700">
                                                <div className="px-4 py-5 flex-auto">
                                                <div className="tab-content tab-space">
                                                    <div className={openTab === 1 ? "block" : "hidden"} id="link1">
                                                    <p>
                                                        OS: Windows® 7/Vista/XP<br/>
                                                        Processor: Intel® Core™ 2 Duo E6600 or AMD Phenom™ X3 8750 processor or better<br/>
                                                        Memory: 2 GB RAM<br/>
                                                        Graphics: Video card must be 256 MB or more and should be a DirectX 9-compatible with support for Pixel Shader 3.0<br/>
                                                        DirectX: Version 9.0c<br/>
                                                        Storage: 15 GB available space<br/>
                                                    </p>
                                                    </div>
                                                    <div className={openTab === 2 ? "block" : "hidden"} id="link2">
                                                    <p>
                                                        CPU: Intel® Core™2 Duo Processor E6600 2.4 GHz or AMD Phenom™ X3 8750 2.4 GHz processor.<br/>
                                                        GPU: Any video card with 256 MB of VRAM or higher.<br/>
                                                        RAM: 2 GB of memory.<br/>
                                                        HDD: 15 GB of free space.<br/>
                                                        OS: Windows XP or higher operating system.<br/>
                                                        DirectX: 9.0c or higher.<br/>
                                                        Shader Model: 3.0 or higher.<br/>
                                                    </p>
                                                    </div>
                                                </div>
                                                </div>
                                            </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div className="col-md-4 col-sm-12 col-12 my-md-0 my-sm-3">
                                <div className="col-12 d-flex flex-column cust-container-top p-3">
                                    <h5 className="text-light">Language Compatibility</h5>
                                    <p className="mx-1 mt-3 text-light">Interface:</p>
                                    <div className="badge bg-primary text-wrap w-16">
                                        [BI_NAME].
                                    </div>
                                    <p className="mx-1 mt-3 text-light">Audio:</p>
                                    <div className="badge bg-primary text-wrap w-16">
                                        [BA_NAME].
                                    </div>
                                    <p className="mx-1 mt-3 text-light">Subtitle:</p>
                                    <div className="badge bg-primary text-wrap w-16">
                                        [BS_NAME].
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
            </Layout>
        </>
    )
}