import Head from "next/head";
import * as React from 'react';

import { FormProvider, FormProviderProps, useForm } from 'react-hook-form';
import { useMutation } from '@tanstack/react-query';
import { useRouter } from 'next/router';
import toast, {Toaster} from "react-hot-toast";
import { apiMock } from '@/lib/apiMock';

import { Carousel } from '@mantine/carousel';
import Layout from "@/Layout/Layout";
import { Search, PlayerTrackNext, PlayerTrackPrev } from 'tabler-icons-react';
import type { InferGetStaticPropsType, GetStaticProps } from 'next';

export type IdData={
    id: String;
}
// perlu revisi style pake tailwind
export default async function GamePage(){
    const router = useRouter();
    const { id } = router.query;
    const user = await apiMock.get(`https://fp-mbd-backend-production-77db.up.railway.app/user/game/${id}`)
    
    return( 
        <>
            <Head>
                <title>Game Page</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <main className="bg-blue-200 dark:bg-slate-800">
                    <div className="container d-flex flex-column px-0 mt-5">
                        <h3 className="ml-2 my-3 text-light">Counter Strike: Global Offensive</h3>

                        <div className="row cust-container-top container d-flex flex-md-row flex-sm-column-reverse flex-column-reverse px-0">
                            
                            <div className="col-md-8 col-sm-12 p-0 d-flex align-center">
                                <div className="embed-responsive embed-responsive-16by9  align-center">
                                    <iframe className="embed-responsive-item" src="https://cdn.akamai.steamstatic.com/steam/apps/81958/movie480.webm?t=1554409259" allowfullscreen></iframe>
                                </div>
                            </div>

                            <div className="col-md-4 col-sm-12 p-3">
                                <img src="https://drive.google.com/uc?export=view&id=1UOX9hzioGUnmgNYEeA2lBtEmson4YIwU" className="img-fluid" style="width: 100%; height: auto;" alt="Game image"/>
                                <div className="G-desk m-2">
                                    <p className="my-0 text-light" style="font-size: .9rem;">The most played online PC action game in the world</p><br/>
                                    <p className="mt-1 mb-0 text-light font-weight-light" style="font-size: .9rem;">Release Date: [G_TGLRILIS]</p>
                                    <p className="mt-1 mb-0 text-light font-weight-light" style="font-size: .9rem;">Developer: [Developer_D_ID]</p>
                                    <p className="mt-1 mb-0 text-light font-weight-light" style="font-size: .9rem;">Release Date: [G_TGLRILIS]</p>
                                    <p className="mt-1 mb-0 text-light font-weight-light" style="font-size: .9rem;">Age Rating: [G_AGERATING]</p>
                                    <p className="mt-1 mb-0 text-light font-weight-light" style="font-size: .9rem;">Tags:</p>
                                    <div className="badge bg-primary text-wrap" style="width: 4rem;">
                                        [G_TAGS].
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div className="row container d-flex flex-md-row flex-sm-column px-0 mt-3">
                            
                            <div className="container col-md-8 col-sm-12 d-flex flex-column m-0 p-0 h-100">

                                <div className="col-12 bg-dark d-block rounded">
                                    <h5 className="ml-2 mt-4 text-light">Play Counter Strike: Global Offensive</h5>
                                    <button className="btn btn-success mb-3 mr-3 float-right" type="buy">Rp 10.000,-</button>
                                </div>

                                <div className="container col-12 my-2 py-3 cust-container-top">

                                    <ul className="nav nav-tabs" id="SysTab" role="tablist">
                                    <li className="nav-item">
                                        <a className="nav-link active bg-transparent text-light" id="minreq-tab" data-toggle="tab" href="#min-req" role="tab" aria-controls="min-req" aria-selected="true">Minimum</a>
                                    </li>
                                    <li className="nav-item">
                                        <a className="nav-link bg-transparent text-light" id="recreq-tab" data-toggle="tab" href="#rec-req" role="tab" aria-controls="rec-req" aria-selected="false">Recommended</a>
                                    </li>
                                    </ul>
                                    
                                    <div className="tab-content mx-2 mt-3">
                                        <div className="tab-pane active" id="min-req" role="tabpanel" aria-labelledby="minreq-tab">
                                            <p className="text-light font-weight-light">OS: Windows® 7/Vista/XP <br/>
                                            Processor: Intel® Core™ 2 Duo E6600 or AMD Phenom™ X3 8750 processor or better<br/>
                                            Memory: 2 GB RAM<br/>
                                            Graphics: Video card must be 256 MB or more and should be a DirectX 9-compatible with support for Pixel Shader 3.0<br/>
                                            DirectX: Version 9.0c<br/>
                                            Storage: 15 GB available space</p>
                                        </div>
                                        <div className="tab-pane" id="rec-req" role="tabpanel" aria-labelledby="recreq-tab">
                                            <p className="text-light font-weight-light">CPU: Intel® Core™2 Duo Processor E6600 2.4 GHz or AMD Phenom™ X3 8750 2.4 GHz processor.<br/>
                                            GPU: Any video card with 256 MB of VRAM or higher.<br/>
                                            RAM: 2 GB of memory.<br/>
                                            HDD: 15 GB of free space.<br/>
                                            OS: Windows XP or higher operating system.<br/>
                                            DirectX: 9.0c or higher.<br/>
                                            Shader Model: 3.0 or higher.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div className="col-md-4 col-sm-12 col-12 my-md-0 my-sm-3">
                                <div className="col-12 d-flex flex-column cust-container-top p-3">
                                    <h5 className="text-light">Language Compatibility</h5>
                                    <p className="mx-1 mt-3 text-light">Interface:</p>
                                    <div className="badge bg-primary text-wrap" style="width: 5rem;">
                                        [BI_NAME].
                                    </div>
                                    <p className="mx-1 mt-3 text-light">Audio:</p>
                                    <div className="badge bg-primary text-wrap" style="width: 5rem;">
                                        [BA_NAME].
                                    </div>
                                    <p className="mx-1 mt-3 text-light">Subtitle:</p>
                                    <div className="badge bg-primary text-wrap" style="width: 5rem;">
                                        [BS_NAME].
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
            </Layout>
        </>
    )
}