import Head from "next/head";
import * as React from 'react';
import Image from 'next/image';

import { FormProvider, FormProviderProps, useForm } from 'react-hook-form';
import { useMutation } from '@tanstack/react-query';
import { useRouter } from 'next/router';
import toast, {Toaster} from "react-hot-toast";
import { apiMock } from '@/lib/apiMock';

import { Carousel } from '@mantine/carousel';
import Layout from "@/Layout/Layout";
import { Search, PlayerTrackNext, PlayerTrackPrev } from 'tabler-icons-react';



export type SearchData = {
    keyword: string;
}

export type Featured={
    G_ID: string;
    G_NAMA: string;
    G_DESKRIPSI: string;
    G_HARGA: number;
    G_PICTURE: string;
}

export default function SearchResultPage(){
    const router = useRouter();
    //const user = await apiMock.get(`https://fp-mbd-backend-production-77db.up.railway.app/user/storeMainPage`)
    const featured =  async () => {await apiMock.get(`https://fp-mbd-backend-production-77db.up.railway.app/user/storeMainPage/featured`)}


    // const { mutate, isSuccess, isError, isLoading } = useMutation(
    //     async ({keyword}: SearchData) => {
    //         await toast.promise(
    //           apiMock.post(`https://fp-mbd-backend-production-77db.up.railway.app/user`, {keyword})
    //          .then( async (res) => {
    //            console.log(res)
    //            const data = res.data.data;
    //         }),
    //         {
    //           success: 'Login Successful',
    //           loading: 'Loading...',
    //           error: (e) =>{
    //             return <p>
    //               {e.response ? e.response.data.message : 'Something went wrong'}
    //             </p>;
    //           }
    //         }
    //         )}
    //       )

    // const onSubmit = ({keyword}: SearchData) => {
    //     //console.log("data", {email, password}); //dummy test
    //     mutate({keyword});
    // }

    const methods = useForm<SearchData>({
        mode: "onChange",
        defaultValues: {
          keyword: "",
        }
      });
    
      const {
        handleSubmit,
        formState,
        reset,
        formState: { errors },
      } = methods;

      React.useEffect(() => {
        if (formState.isSubmitSuccessful) {
          reset({
            keyword: "",
          });
        }
      }, [formState, reset]);

    return(
        <>
            <Head>
                <title>Search Result</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
            <main className="bg-blue-200 dark:bg-slate-800">
                <section>
                <div className="px-[15%] pt-5">
                    <FormProvider {...methods}>
                        {/* <form onSubmit={handleSubmit(onSubmit)}> */}
                            <label htmlFor="default-search" className="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-white">Search</label>
                            <div className="relative">
                                <div className="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                                    <svg aria-hidden="true" className="w-5 h-5 text-gray-500 dark:text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path></svg>
                                </div>
                                <input type="search" id="default-search" className="block w-full p-4 pl-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Search Games, Tags..." required/>
                                <button type="submit" className="text-white absolute right-2.5 bottom-2.5 bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"><Search size={20} color="white"/></button>
                            </div>
                        {/* </form> */}
                    </FormProvider>
                </div>
                </section>
                <div className="px-[15%] py-5">
                    <p>POPULAR</p>
                </div>
                <div className="w-2/3 mx-auto">
                    <div className="w-full flex flex-row">
                        <div className="w-3/4">
                        <a href="#" className="flex flex-col items-center bg-white border border-gray-200 rounded-lg shadow md:flex-row w-full hover:bg-gray-100 dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-700 mb-3">
                                <Image height={500} width={500} className="object-cover h-full w-auto rounded-t-lg md:h-auto md:w-48 md:rounded-none md:rounded-l-lg" src="https://drive.google.com/uc?export=view&id=1_jTTRDcgx3qJa6hI-PSbR-EDGJ_Rup8N" alt=""/>
                                <div className="flex flex-col justify-between p-4 leading-normal pl-5 w-1/3 sm:w-full">
                                    <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">STRAY</h5>
                                    <p className="font-normal text-gray-700 dark:text-gray-400">Adventure, Strategy, Open World</p>
                                </div>
                                <div className="flex flex-col p-4 leading-normal pl-5 w-full items-end">
                                    <p className="font-semibold text-gray-700 dark:text-white p-0 md:pr-8">Rp80000</p>
                                </div>
                            </a>
                            <a href="#" className="flex flex-col items-center bg-white border border-gray-200 rounded-lg shadow md:flex-row w-full hover:bg-gray-100 dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-700 mb-3">
                                <Image height={500} width={500} className="object-cover h-full w-auto rounded-t-lg md:h-auto md:w-48 md:rounded-none md:rounded-l-lg" src="https://drive.google.com/uc?export=view&id=178HEwH3W3bXD52D7hL1Q2-7GyBAr6W7q" alt=""/>
                                <div className="flex flex-col justify-between p-4 leading-normal pl-5 w-1/3 sm:w-full">
                                    <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Monster Hunter</h5>
                                    <p className="font-normal text-gray-700 dark:text-gray-400">Action, Multiplayer, Open World</p>
                                </div>
                                <div className="flex flex-col p-4 leading-normal pl-5 w-full items-end">
                                    <p className="font-semibold text-gray-700 dark:text-white p-0 md:pr-8">Rp300000</p>
                                </div>
                            </a>
                        </div>
                        <div className="w-1/4 px-5">
                            <div className="w-full">
                                <p>Search By Tags</p>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
            </Layout>
        </>
    )
}