import Head from "next/head";
import * as React from 'react';
import Image from 'next/image';

import { FormProvider, FormProviderProps, useForm } from 'react-hook-form';
import { useMutation } from '@tanstack/react-query';
import { useRouter } from 'next/router';
import toast, {Toaster} from "react-hot-toast";
import { apiMock } from '@/lib/apiMock';

import { Carousel } from '@mantine/carousel';
import Layout from "@/Layout/Layout";
import { PlayerPlay, Search} from 'tabler-icons-react';

export default function Library(){
    const [openTab, setOpenTab] = React.useState(1);
    return(
        <>
            <Head>
                <title>Profile Page</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
            <main className="bg-blue-200 dark:bg-slate-800 p-12 flex flex-wrap justify-center gap-4">
                <div className="flex flex-col items-center bg-white border border-gray-200 rounded-lg shadow dark:border-gray-700 dark:bg-gray-800 mb-3 w-96 h-72">
                    <Image height={500} width={500} className="object-cover w-full h-auto rounded-t-lg md:rounded-none md:rounded-l-lg" src="https://drive.google.com/uc?export=view&id=1s8E2fVvfR-oCzjYx3A9pL9-h7NrVGzKL" alt=""/>
                    <div className="flex flex-row p-0 sm:p-4 leading-normal items-center pl-2 sm:pl-5 w-full gap-5">
                        <button className='bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded float-right'><PlayerPlay/></button><h5 className="mb-2 text-sm font-bold tracking-tight text-gray-900 dark:text-white">Stray - Original Soundtrack</h5>
                    </div>
                </div>
                <div className="flex flex-col items-center bg-white border border-gray-200 rounded-lg shadow dark:border-gray-700 dark:bg-gray-800 mb-3 w-96 h-72">
                    <Image height={500} width={500} className="object-cover w-full h-auto rounded-t-lg md:rounded-none md:rounded-l-lg" src="https://drive.google.com/uc?export=view&id=1s8E2fVvfR-oCzjYx3A9pL9-h7NrVGzKL" alt=""/>
                    <div className="flex flex-row p-0 sm:p-4 leading-normal items-center pl-2 sm:pl-5 w-full gap-5">
                        <button className='bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded float-right'><PlayerPlay/></button><h5 className="mb-2 text-sm font-bold tracking-tight text-gray-900 dark:text-white">Stray - Original Soundtrack</h5>
                    </div>
                </div>
                <div className="flex flex-col items-center bg-white border border-gray-200 rounded-lg shadow dark:border-gray-700 dark:bg-gray-800 mb-3 w-96 h-72">
                    <Image height={500} width={500} className="object-cover w-full h-auto rounded-t-lg md:rounded-none md:rounded-l-lg" src="https://drive.google.com/uc?export=view&id=1s8E2fVvfR-oCzjYx3A9pL9-h7NrVGzKL" alt=""/>
                    <div className="flex flex-row p-0 sm:p-4 leading-normal items-center pl-2 sm:pl-5 w-full gap-5">
                        <button className='bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded float-right'><PlayerPlay/></button><h5 className="mb-2 text-sm font-bold tracking-tight text-gray-900 dark:text-white">Stray - Original Soundtrack</h5>
                    </div>
                </div>
                <div className="flex flex-col items-center bg-white border border-gray-200 rounded-lg shadow dark:border-gray-700 dark:bg-gray-800 mb-3 w-96 h-72">
                    <Image height={500} width={500} className="object-cover w-full h-auto rounded-t-lg md:rounded-none md:rounded-l-lg" src="https://drive.google.com/uc?export=view&id=1s8E2fVvfR-oCzjYx3A9pL9-h7NrVGzKL" alt=""/>
                    <div className="flex flex-row p-0 sm:p-4 leading-normal items-center pl-2 sm:pl-5 w-full gap-5">
                        <button className='bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded float-right'><PlayerPlay/></button><h5 className="mb-2 text-sm font-bold tracking-tight text-gray-900 dark:text-white">Stray - Original Soundtrack</h5>
                    </div>
                </div>
                <div className="flex flex-col items-center bg-white border border-gray-200 rounded-lg shadow dark:border-gray-700 dark:bg-gray-800 mb-3 w-96 h-72">
                    <Image height={500} width={500} className="object-cover w-full h-auto rounded-t-lg md:rounded-none md:rounded-l-lg" src="https://drive.google.com/uc?export=view&id=1s8E2fVvfR-oCzjYx3A9pL9-h7NrVGzKL" alt=""/>
                    <div className="flex flex-row p-0 sm:p-4 leading-normal items-center pl-2 sm:pl-5 w-full gap-5">
                        <button className='bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded float-right'><PlayerPlay/></button><h5 className="mb-2 text-sm font-bold tracking-tight text-gray-900 dark:text-white">Stray - Original Soundtrack</h5>
                    </div>
                </div>

            </main>
            </Layout>
        </>
    )
}