import Head from "next/head";
import * as React from 'react';
import Image from 'next/image';

import { FormProvider, FormProviderProps, useForm } from 'react-hook-form';
import { useMutation } from '@tanstack/react-query';
import { useRouter } from 'next/router';
import toast, {Toaster} from "react-hot-toast";
import { apiMock } from '@/lib/apiMock';

import { Carousel } from '@mantine/carousel';
import Layout from "@/Layout/Layout";
import { Search, PlayerTrackNext, PlayerTrackPrev } from 'tabler-icons-react';

export type SearchData = {
    keyword: string;
}

export default function SearchResultPage(){
    const router = useRouter();
    const { keyword } = router.query;
    //console.log(id);
    //const user = await apiMock.get(`https://fp-mbd-backend-production-77db.up.railway.app/user/storeMainPage`)
    //const featured =  async () => {await apiMock.get(`https://fp-mbd-backend-production-77db.up.railway.app/user/storeMainPage/featured`)}


    // const { mutate, isSuccess, isError, isLoading } = useMutation(
    //     async ({keyword}: SearchData) => {
    //         await toast.promise(
    //           apiMock.post(`https://fp-mbd-backend-production-77db.up.railway.app/user`, {keyword})
    //          .then( async (res) => {
    //            console.log(res)
    //            const data = res.data.data;
    //         }),
    //         {
    //           success: 'Login Successful',
    //           loading: 'Loading...',
    //           error: (e) =>{
    //             return <p>
    //               {e.response ? e.response.data.message : 'Something went wrong'}
    //             </p>;
    //           }
    //         }
    //         )}
    //       )

    // const onSubmit = ({keyword}: SearchData) => {
    //     //console.log("data", {email, password}); //dummy test
    //     mutate({keyword});
    // }

    const methods = useForm<SearchData>({
        mode: "onChange",
        defaultValues: {
          keyword: "",
        }
      });
    
      const {
        handleSubmit,
        formState,
        reset,
        formState: { errors },
      } = methods;

      React.useEffect(() => {
        if (formState.isSubmitSuccessful) {
          reset({
            keyword: "",
          });
        }
      }, [formState, reset]);

    return(
        <>
            <Head>
                <title>Search Result</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <script src="https://unpkg.com/@themesberg/flowbite@latest/dist/flowbite.bundle.js"></script>
            </Head>
            <Layout>
            <main className="bg-blue-200 dark:bg-slate-800 min-h-[85vh]">
                <section>
                <div className="px-[15%] pt-5">
                    <FormProvider {...methods}>
                        {/* <form onSubmit={handleSubmit(onSubmit)}> */}
                            <label htmlFor="default-search" className="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-white">Search</label>
                            <div className="relative">
                                <div className="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                                    <svg aria-hidden="true" className="w-5 h-5 text-gray-500 dark:text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" strokeWidth="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path></svg>
                                </div>
                                <input type="search" id="default-search" className="block w-full p-4 pl-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Search Games, Tags..." required/>
                                <button type="submit" className="text-white absolute right-2.5 bottom-2.5 bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"><Search size={20} color="white"/></button>
                            </div>
                        {/* </form> */}
                    </FormProvider>
                </div>
                </section>
                <div className="px-[5%] lg:px-[10%] py-5">
                    <p>Search results for "{keyword}"</p>
                </div>
                <div className="w-11/12 lg:w-4/5 mx-auto">
                    <div className="w-full flex flex-col-reverse lg:flex-row">
                        <div className="w-full lg:w-[full-52]">
                            <a href="#" className="flex flex-col items-center bg-white border border-gray-200 rounded-lg shadow md:flex-row w-full hover:bg-gray-100 dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-700 mb-3">
                                <Image height={500} width={500} className="object-cover h-full w-auto rounded-t-lg md:h-auto md:w-48 md:rounded-none md:rounded-l-lg" src="https://drive.google.com/uc?export=view&id=1_jTTRDcgx3qJa6hI-PSbR-EDGJ_Rup8N" alt=""/>
                                <div className="flex flex-col justify-between p-4 leading-normal pl-5 w-full">
                                    <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">STRAY</h5>
                                    <p className="font-normal text-gray-700 dark:text-gray-400">Adventure, Strategy, Open World</p>
                                </div>
                                <div className="flex flex-col p-4 leading-normal pl-5 w-full items-end">
                                    <p className="font-semibold text-gray-700 dark:text-white p-0 md:pr-8">Rp80000</p>
                                </div>
                            </a>
                            <a href="#" className="flex flex-col items-center bg-white border border-gray-200 rounded-lg shadow md:flex-row w-full hover:bg-gray-100 dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-700 mb-3">
                                <Image height={500} width={500} className="object-cover h-full w-auto rounded-t-lg md:h-auto md:w-48 md:rounded-none md:rounded-l-lg" src="https://drive.google.com/uc?export=view&id=178HEwH3W3bXD52D7hL1Q2-7GyBAr6W7q" alt=""/>
                                <div className="flex flex-col justify-between p-4 leading-normal pl-5 w-full">
                                    <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Monster Hunter</h5>
                                    <p className="font-normal text-gray-700 dark:text-gray-400">Action, Multiplayer, Open World</p>
                                </div>
                                <div className="flex flex-col p-4 leading-normal pl-5 w-full items-end">
                                    <p className="font-semibold text-gray-700 dark:text-white p-0 md:pr-8">Rp300000</p>
                                </div>
                            </a>
                        </div>
                        <div className="w-full lg:w-52">
                            <div className="w-full mx-0 lg:mx-5 mb-5 lg:mb-0 flex flex-row lg:flex-col gap-4">
                                <div className="w-1/4 lg:w-full">
                                    <button id="tagsDropdownButton" data-dropdown-toggle="tagsDropdown" className="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm pl-3 pr-2 py-2.5 text-center inline-flex items-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" type="button">
                                        <p className="w-5/6 text-left">Search tags</p>
                                        <svg className="w-1/6 h-4" aria-hidden="true" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path>
                                        </svg>
                                    </button>
                                    <div id="tagsDropdown" className="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700">
                                        <ul className="py-2 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="tagsDropdownButton">
                                        <li>
                                            <a href="#" className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">[T_NAMA]</a>
                                        </li>
                                        <li>
                                            <a href="#" className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">[T_NAMA]</a>
                                        </li>
                                        <li>
                                            <a href="#" className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">[T_NAMA]</a>
                                        </li>
                                        <li>
                                            <a href="#" className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">[T_NAMA]</a>
                                        </li>
                                        </ul>
                                    </div>
                                </div>
                                <div className="w-1/4 lg:w-full">
                                    <button id="languageDefaultButton" data-dropdown-toggle="LanguageDropdown" className="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm pl-3 pr-2 py-2.5 text-center inline-flex items-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" type="button">
                                        <p className="w-5/6 text-left">Search Language</p>
                                        <svg className="w-1/6 h-4" aria-hidden="true" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path>
                                        </svg>
                                    </button>
                                    <div id="LanguageDropdown" className="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700">
                                        <ul className="py-2 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdownDefaultButton">
                                        <li>
                                            <a onClick={() =>
                                            router.push({
                                                pathname: '/searchResultPage',
                                                query: { keyword: 'Indonesian' },
                                              })}
                                            className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Indonesian</a>
                                        </li>
                                        <li>
                                            <a href="#" className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">English</a>
                                        </li>
                                        <li>
                                            <a href="#" className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Korean</a>
                                        </li>
                                        <li>
                                            <a href="#" className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Japanese</a>
                                        </li>
                                        <li>
                                            <a href="#" className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">French</a>
                                        </li>
                                        <li>
                                            <a href="#" className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Danish</a>
                                        </li>
                                        <li>
                                            <a href="#" className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Dutch</a>
                                        </li>
                                        <li>
                                            <a href="#" className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Italian</a>
                                        </li>
                                        <li>
                                            <a href="#" className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Hungarian</a>
                                        </li>
                                        <li>
                                            <a href="#" className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Norwegian</a>
                                        </li>
                                        <li>
                                            <a href="#" className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Thai</a>
                                        </li>
                                        <li>
                                            <a href="#" className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Russian</a>
                                        </li>
                                        <li>
                                            <a href="#" className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Spanish</a>
                                        </li>
                                        <li>
                                            <a href="#" className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Ukrainian</a>
                                        </li>
                                        <li>
                                            <a href="#" className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Vietnamese</a>
                                        </li>
                                        <li>
                                            <a href="#" className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Greek</a>
                                        </li>
                                        <li>
                                            <a href="#" className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Turkish</a>
                                        </li>
                                        <li>
                                            <a href="#" className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Swedish</a>
                                        </li>
                                        <li>
                                            <a href="#" className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Portuguese</a>
                                        </li>
                                        <li>
                                            <a href="#" className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Czech</a>
                                        </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
            </Layout>
        </>
    )
}